import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAdmin, jsonError } from "@/lib/apiHelpers";

// Plain GET, no dynamic route segment, reads the DB — force-dynamic (see
// note in ../products/route.ts).
export const dynamic = "force-dynamic";

/**
 * Single-barcode lookup, used as a fallback by the POS page whenever the
 * scanned code isn't already in the catalog it preloaded (e.g. a label was
 * generated by a second staff member on another device after the POS page
 * was opened).
 */
export async function GET(req: NextRequest) {
  const { admin, response } = requireAdmin(req, ["MERCH_STAFF"]);
  if (!admin) return response;

  const barcode = req.nextUrl.searchParams.get("barcode")?.trim();
  if (!barcode) return jsonError("MISSING_BARCODE");

  const stock = await prisma.merchProductStock.findUnique({
    where: { barcode },
    include: { product: true },
  });
  if (!stock || !stock.product || !stock.product.active) {
    return jsonError("ไม่พบสินค้าสำหรับบาร์โค้ดนี้ หรือสินค้าถูกปิดการขายแล้ว", 404);
  }

  return NextResponse.json({
    stockId: stock.id,
    barcode: stock.barcode,
    productId: stock.productId,
    productName: stock.product.name,
    size: stock.size,
    price: stock.product.price,
    quantity: stock.quantity,
  });
}
